spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring_criteria
    username: root
    password:
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: none
#      show-sql: true
#    properties:
#      hibernate.jdbc.lob.non_contextual_creation: true
management:
  endpoints:
    web:
      #base-path: /management
      exposure:
        include: [ 'configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump' ]
#jasypt:
#  encryptor:
#    password: Mic2020@!@#@
#    bean: jasyptStringEncryptor